version: '3.6'
services:
  minimal-packager:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.package
    volumes:
      - .:/app/build

  publisher:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.publisher
      args:
        - BUILDKITE=${BUILDKITE}
        - REG_BASIC_CREDENTIAL
        - REG_NPM_EMAIL
        - PUBLISH_URL
        - BRANCH_NAME

  ci:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.ci

  browser-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.browser
      target: browser-maze-runner
      args:
        - BUILDKITE_BUILD_NUMBER
    command: --fail-fast --retry 2
    environment:
      VERBOSE:
      DEBUG:
      BROWSER: "${BROWSER:-chrome_61}"
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}
      HOST: "${HOST:-maze-runner}"
      API_HOST: "${API_HOST:-maze-runner}"
    networks:
      default:
        aliases:
          - maze-runner

  node-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.node
      target: node-maze-runner
    command: --fail-fast --retry 2
    environment:
      NODE_VERSION: "${NODE_VERSION:-10}"
      COMPOSE_PROJECT_NAME: "node${NODE_VERSION:-10}"
      NETWORK_NAME: "${BUILDKITE_JOB_ID:-js-maze-runner}"
      VERBOSE:
      DEBUG:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  expo-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo
      args:
        - BUILDKITE_BUILD_NUMBER
    command: --fail-fast --retry 2
    environment:
      VERBOSE:
      DEBUG:
      BROWSER_STACK_USERNAME:
      BROWSER_STACK_ACCESS_KEY:
      BROWSER_STACK_LOCAL_IDENTIFIER: ${BUILDKITE_JOB_ID:-maze-runner}
      APP_LOCATION:
      DEVICE_TYPE:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/expo/build

  expo-publisher:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo-publisher
    environment:
      EXPO_USERNAME:
      EXPO_PASSWORD:
      EXPO_RELEASE_CHANNEL:
    networks:
      default:
        aliases:
          - maze-runner

  expo-android-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.expo-android-builder
    environment:
      VERBOSE:
      DEBUG:
      EXPO_USERNAME:
      EXPO_PASSWORD:
      EXPO_RELEASE_CHANNEL:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/expo/features/fixtures/build

  react-native-android-builder:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.react-native-android-builder
      args:
        - REG_BASIC_CREDENTIAL
        - REG_NPM_EMAIL
    environment:
      - VERBOSE
      - DEBUG
      - BRANCH_NAME
      - BUILDKITE
      - REGISTRY_URL
      - REACT_NATIVE_VERSION
      - NOTIFIER_VERSION
      - ARTEFACT_NAME
      - JS_SOURCE_DIR
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/build
      - ./test:/app/test

  react-native-maze-runner:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.react-native
      args:
        - BUILDKITE_BUILD_NUMBER
    environment:
      VERBOSE:
      DEBUG:
      SKIP_NAVIGATION_SCENARIOS:
    networks:
      default:
        aliases:
          - maze-runner
    volumes:
      - ./build:/app/test/react-native/build

networks:
  default:
    name: ${BUILDKITE_JOB_ID:-js-maze-runner}
